### ISSUE TITLE
V2 seems to be imcompatible with gradle 6

### ISSUE THREAD

**Issue by modmuss50** [Wyn-Price/CurseMaven-OLD#10]
After updating to gradle 6 (5.6.3 works) it no longer seems to be able to reslove the dependencys.

Could be related to [this](https://discuss.gradle.org/t/how-to-fetch-maven-artifact-without-pom-file-in-gradle-6-0/33836)

`modCompile "curse.maven:modmenu:2837462"` is what im using.

Output log: [gist](https://gist.github.com/modmuss50/737e377fffb5800566eef08c43eb59dc)

Using fabric loom 0.2.7 with Java 12.0.1

**Comment by Wyn-Price** [comment]
Hmm. It's possible the method name has changed, thus the following never gets called:
https://github.com/Wyn-Price/CurseMaven/blob/a79f11650248942490f577c09afda6165d4feee1/src/main/groovy/com/wynprice/cursemaven/CurseMavenPlugin.groovy#L39-L52 

It's unfortunate I have to the above to get cursemaven to work, but desperate times call for desperate measures. 

I'm looking into it.

**Comment by Suya1671** [comment]
any updates?
