### ISSUE TITLE
DDoS protection by Cloudflare

### ISSUE THREAD

**Issue by jihuayu** [Wyn-Price/CurseMaven-OLD#11]
Could not download the file.Beacuse the page(https://www.curseforge.com/minecraft/mc-mods/bookshelf/download/2831582/file) is DDoS protection by Cloudflare.
![image](https://user-images.githubusercontent.com/32858525/81139559-bdc7a480-8f98-11ea-8228-87ffd00a639f.png)

It will download this html.
You can use api `https://addons-ecs.forgesvc.net/api/v2/addon/${addonID}/file/${fileID}/download-url`,to get the url.

**Comment by Wyn-Price** [comment]
I do use that api, what version are you on

**Comment by jihuayu** [comment]
Oh,I am very sorry.I use 1.2.+
I copy the code from other project.
Thanks
