### ISSUE TITLE
[Question] Adding sources to the mod

### ISSUE THREAD

**Issue by TimeConqueror** [Wyn-Price/CurseMaven-OLD#12]
Hello! I didn't find any information of how to download basic mod version with sources.
I can attach mod as here:
`deobfCompile "curse.maven:just-enough-resources-jer:2728585"`
(https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer/files/2728585)
But is there a way to attach sources file along with the basic one?

**Comment by Wyn-Price** [comment]
the `-sources` jar *should* be picked up. I'm assuming it's not ?

**Comment by TimeConqueror** [comment]
Yeah, it doesn't apply sources, only base file

**Comment by Wyn-Price** [comment]
Can i have your full `build.gradle` and the gradle version you're using

**Comment by TimeConqueror** [comment]
Yeah, you can check it here: https://github.com/TheSlayerMC/Journey-Into-The-Light
