### ISSUE TITLE
CloudFlare Blocking access

### ISSUE THREAD

**Issue by SeanLatimer** [Wyn-Price/CurseMaven-OLD#6]
CloudFlare seems to be blocking access to CurseForge for non-browser applications.

`Caused by: org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://www.curseforge.com/minecraft/mc-mods/laggoggles/files/2757184`

This can also be verified by running a curl.
`curl -I -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0" http://www.curseforge.com/minecraft/mc-mods/laggoggles/files/2757184`

**Comment by Wyn-Price** [comment]
Before I make a new release, I want to restructure the plugin a bit. Rather than have the downloading done at configuration time, it should be done somewhere else, due to the new http client having to take a couple of seconds to scrape the page.

**Comment by p455w0rd** [comment]
so is this just broken for now? the commit says version=1.2.3, but gradle complains that it can't find that version
```C:\mc_modding\CapabilityStages>gradlew setupDecompWorkspace eclipse

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\mc_modding\CapabilityStages\build.gradle' line: 17

* What went wrong:
Plugin [id: 'com.wynprice.cursemaven', version: '1.2.3'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.wynprice.cursemaven:com.wynprice.cursemaven.gradle.plugin:1.2.3')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

and 1.2.2 complains about the 403 response

**Comment by Wyn-Price** [comment]
The version isn't released yet, as stated above. However, some people have used jitpack to run 1.2.3, and have reported that the 403 issues still occur, so I'll have to do some more digging. 

It's difficult, as curse have essentially turned on the setting that exists just to stop web scrapers, and the only way bypass it seems to be to simulate the entire browser (which is what 1.2.3 does)

**Comment by Wyn-Price** [comment]
Reclosed by (https://github.com/Wyn-Price/CurseMaven/commit/bcf1dd392958b8ced77480ac042b843c21148a3c)
