### ISSUE TITLE
Incompatible with 1.14

### ISSUE THREAD

**Issue by Sunconure11** [Wyn-Price/CurseMaven-OLD#7]
Due to changes in commands used by forge on 1.14, this is technically incompatible with those versions. Would it be possible to add support for 1.14 later on?

**Comment by Wyn-Price** [comment]
This should work on 1.14 still. It's just `fg.deobf(curse.resolve("foo","bar"))`. Besides, I am planning on restructuring everything soon, so you would do `fg.deobf("curse.resolve:foo:bar")` instead.

**Comment by Wyn-Price** [comment]
Can you try with versions 2.1.0? The `curse.resolve` is gone. Look at the README for documentation.

**Comment by pupnewfster** [comment]
One thing that seems to be odd, is I am unable to get it working with `compileOnly` and `runtimeOnly`, unless I first use `compile` and then switch to one of the others. Granted I tested in 1.15, not 1.14 I believe FG is the same for both.

For example:
```
compileOnly fg.deobf("curse.maven:projecte:2882000")
runtimeOnly fg.deobf("curse.maven:projecte:2881997")
```
does not work and gives errors of being unable to resolve either, but if I say use:
```
compile fg.deobf("curse.maven:projecte:2882000")
```
it is then able to resolve the file, and then I can also change it back to `compileOnly` for that file (though I am holding off on doing so as I presume then other people won't be able to get it building properly without modifying it to compile first)

**Comment by Wyn-Price** [comment]
@pupnewfster does this issue still occur?

**Comment by pupnewfster** [comment]
It seems to, updating curse maven to 2.1.3, and then switching which lines are commented out and which are not here: https://github.com/mekanism/Mekanism/blob/1.15x/build.gradle#L282-L284 causes this error to appear when attempting to refresh the build.gradle:
```
Could not find curse.maven:projecte:2898247_mapped_snapshot_20200504-1.15.1.
Searched in the following locations:
  - https://edge.forgecdn.net/curse/maven/projecte/2898247_mapped_snapshot_20200504-1.15.1/projecte-2898247_mapped_snapshot_20200504-1.15.1.jar
  - https://files.minecraftforge.net/maven/curse/maven/projecte/2898247_mapped_snapshot_20200504-1.15.1/projecte-2898247_mapped_snapshot_20200504-1.15.1.pom
  - https://files.minecraftforge.net/maven/curse/maven/projecte/2898247_mapped_snapshot_20200504-1.15.1/projecte-2898247_mapped_snapshot_20200504-1.15.1.jar
  - http://dvs1.progwml6.com/files/maven/curse/maven/projecte/2898247_mapped_snapshot_20200504-1.15.1/projecte-2898247_mapped_snapshot_20200504-1.15.1.pom
  - http://dvs1.progwml6.com/files/maven/curse/maven/projecte/2898247_mapped_snapshot_20200504-1.15.1/projecte-2898247_mapped_snapshot_20200504-1.15.1.jar
  - https://minecraft.curseforge.com/api/maven/curse/maven/projecte/2898247_mapped_snapshot_20200504-1.15.1/projecte-2898247_mapped_snapshot_20200504-1.15.1.pom
  - https://minecraft.curseforge.com/api/maven/curse/maven/projecte/2898247_mapped_snapshot_20200504-1.15.1/projecte-2898247_mapped_snapshot_20200504-1.15.1.jar
  - https://maven.tterrag.com/curse/maven/projecte/2898247_mapped_snapshot_20200504-1.15.1/projecte-2898247_mapped_snapshot_20200504-1.15.1.pom
  - https://maven.tterrag.com/curse/maven/projecte/2898247_mapped_snapshot_20200504-1.15.1/projecte-2898247_mapped_snapshot_20200504-1.15.1.jar
  - https://maven.blamejared.com/curse/maven/projecte/2898247_mapped_snapshot_20200504-1.15.1/projecte-2898247_mapped_snapshot_20200504-1.15.1.pom
  - https://maven.blamejared.com/curse/maven/projecte/2898247_mapped_snapshot_20200504-1.15.1/projecte-2898247_mapped_snapshot_20200504-1.15.1.jar
  - https://files.minecraftforge.net/maven/curse/maven/projecte/2898247_mapped_snapshot_20200504-1.15.1/projecte-2898247_mapped_snapshot_20200504-1.15.1.pom
  - https://files.minecraftforge.net/maven/curse/maven/projecte/2898247_mapped_snapshot_20200504-1.15.1/projecte-2898247_mapped_snapshot_20200504-1.15.1.jar
  - file:/C:/Users/Richard/.gradle/caches/forge_gradle/bundeled_repo/curse/maven/projecte/2898247_mapped_snapshot_20200504-1.15.1/projecte-2898247_mapped_snapshot_20200504-1.15.1.pom
  - file:/C:/Users/Richard/.gradle/caches/forge_gradle/bundeled_repo/curse/maven/projecte/2898247_mapped_snapshot_20200504-1.15.1/projecte-2898247_mapped_snapshot_20200504-1.15.1.jar
  - https://libraries.minecraft.net/curse/maven/projecte/2898247_mapped_snapshot_20200504-1.15.1/projecte-2898247_mapped_snapshot_20200504-1.15.1.jar
  - https://repo.maven.apache.org/maven2/curse/maven/projecte/2898247_mapped_snapshot_20200504-1.15.1/projecte-2898247_mapped_snapshot_20200504-1.15.1.pom
  - https://repo.maven.apache.org/maven2/curse/maven/projecte/2898247_mapped_snapshot_20200504-1.15.1/projecte-2898247_mapped_snapshot_20200504-1.15.1.jar
Required by:
    project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

**Comment by Wyn-Price** [comment]
So this appears to be an issue relating to forge gradle. The version passed to the maven pattern is `2898247_mapped_snapshot_20200504-1.15.1`, rather than `2898247`, hence curse maven doesn't try to resolve it. This i can fix

**Comment by Wyn-Price** [comment]
Is the issue solved with 2.1.4?

**Comment by pupnewfster** [comment]
Yes it seems to be fixed, thank you.

**Comment by Wyn-Price** [comment]
Im sorry it took so long

**Comment by pupnewfster** [comment]
No problem, I may end up opening an issue this weekend as on slightly further testing while it does properly compile now (with `compileOnly` and `runtimeOnly`) for some reason `runtimeOnly` doesn't seem to actually cause the dependency to be loaded with `runClient`. Holding off on that for now though as this is my final week in the semester I am busy with classes and want to experiment more, given it doesn't throw any errors and `compileOnly` works as intended so it seems semi unlikely to me that `runtimeOnly` not doing anything is an issue with this plugin.

**Comment by pupnewfster** [comment]
Ya no idea what is going on/why it doesn't work though I don't think it necessarily has to do with CurseMaven so not going ahead and opening an issue. Turns out some of the time it *does* work with `runtimeOnly` and sometimes it does not. The one where it more consistently doesn't work is my `datagenmainRuntimeOnly` but that is not as big a deal given using `datagenmainCompile` isn't going to end up causing any accidental hard dependencies at runtime of the mod. Most likely it is just some weird interaction between my setup, forgegradle, and cursemaven that causes something to be *slightly* off sometimes.
