### ISSUE TITLE
Some files cannot be downloaded

### ISSUE THREAD

**Issue by TheLMiffy1111** [Wyn-Price/CurseMaven-OLD#8]
Was trying to update dependencies and noticed that files were empty, and there was this error message:
```An error occurred attempting to initialize the dependency 'Cobalt.NiceDates'
[CurseMavenRepo] Getting binary at https://www.curseforge.com/minecraft/mc-mods/silents_mechanisms/download/2807890/fil
Error during JavaScriptEngine.init(WebWindow, Context)
TypeError: Cannot modify readonly property: constructor. (https://c.amazon-adsystem.com/aax2/apstag.js#2)
prototype: HTMLOptionElement
Error during JavaScriptEngine.init(WebWindow, Context)
TypeError: Cannot modify readonly property: constructor. (https://c.amazon-adsystem.com/aax2/apstag.js#2)
prototype: MutationObserver
Error during JavaScriptEngine.init(WebWindow, Context)
TypeError: Cannot modify readonly property: constructor. (https://c.amazon-adsystem.com/aax2/apstag.js#2)
prototype: URL

**Comment by Wyn-Price** [comment]
The dependency should still have been download. This is just log spam that I'm working on fixing

**Comment by TheLMiffy1111** [comment]
I think it's because of the URL being incorrect

**Comment by Wyn-Price** [comment]
Can I see your `build.gradle`?

**Comment by TheLMiffy1111** [comment]
https://github.com/TheLMiffy1111/JAOPCA/blob/38cabb0ce06d0b01ad54a927a0797aefeacf231d/build.gradle

**Comment by Wyn-Price** [comment]
Just noticed the `fil` at the end. That should be `file`. That's literally impossible to happen: https://github.com/Wyn-Price/CurseMaven/blob/f0d58155e6395615fa2f557d8a5dbc52e2761809/src/main/groovy/com/wynprice/cursemaven/repo/CurseMavenRepo.groovy#L71 
I'm currently in school, so I can't test it out for myself, but once I get home I'll be able to.

**Comment by Wyn-Price** [comment]
I tried with your `build.gradle` and it all worked for me

**Comment by TheLMiffy1111** [comment]
I guess I'll close this for now

**Comment by Wyn-Price** [comment]
Try with version 2.1.0. it's completely different and should work
